---
extends: eslint:recommended
env:
  browser: true
  jquery: true
ecmaFeatures:
  arrowFunctions: true
  blockBindings: true
  classes: true
  destructuring: true
  modules: true
  spread: true
  templateStrings: true
rules:
  quotes:
    - 2
    - single
  semi: 2
  no-unused-vars: 0
  no-console: 0
