---
extends: airbnb
env:
  browser: true
  jquery: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  quotes:
    - 2
    - single
  no-unused-vars: 0
  no-console: 0
  indent: 0
  import/no-unresolved: 0
  prefer-template: 0
  max-len: 0
  spaced-comment: 0
  object-shorthand: 0
  arrow-body-style: 0
  no-useless-concat: 0
  no-param-reassign: 0
  consistent-return: 0
  newline-per-chained-call: 0
  prefer-rest-params: 0
  no-new: 0
  array-callback-return: 0
  no-useless-escape: 0
  no-confusing-arrow: 0
  new-cap: 0
  global-require: 0
  default-case: 0
  comma-dangle: 0
